import { useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Grid, LinearProgress, Stack, Typography } from '@mui/material'
import RefreshIcon from '@mui/icons-material/Refresh'
import { api } from '../api.js'
function metricPercent(metric) { return typeof metric.maximum === 'number' && metric.maximum > 0 && typeof metric.value === 'number' ? Math.min(100, Math.max(0, (metric.value / metric.maximum) * 100)) : null }
function UsageCard({ item }) {
  const { config, latest } = item
  const color = latest?.status === 'healthy' ? 'success' : latest?.status === 'error' ? 'error' : 'warning'
  return <Card variant="outlined" sx={{ height: '100%' }}><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center" gap={2}><Box><Typography variant="overline" color="text.secondary">{config.provider}</Typography><Typography variant="h6">{config.label}</Typography></Box><Chip color={color} label={latest?.status || 'not polled'} size="small" /></Stack><Typography sx={{ mt: 2, mb: 2 }} color="text.secondary">{latest?.summary || 'No usage snapshot yet. Hit refresh; summon data from the void.'}</Typography><Stack gap={2}>{(latest?.metrics || []).map((metric) => { const percent = metricPercent(metric); return <Box key={metric.label}><Stack direction="row" justifyContent="space-between"><Typography variant="body2">{metric.label.replaceAll('_', ' ')}</Typography><Typography variant="body2" color="text.secondary">{String(metric.value ?? '—')} {metric.unit || ''}</Typography></Stack>{percent !== null && <LinearProgress variant="determinate" value={percent} sx={{ mt: 0.75 }} />}</Box> })}</Stack>{latest?.error && <Alert severity="error" sx={{ mt: 2 }}>{latest.error}</Alert>}</CardContent></Card>
}
export default function DashboardPage() {
  const [items, setItems] = useState([]); const [homepage, setHomepage] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load(poll = false) { setLoading(true); setError(''); try { if (poll) await api.pollAll(); const [usage, hp] = await Promise.all([api.usage(), api.homepage()]); setItems(usage); setHomepage(hp) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  return <Stack gap={3}><Stack direction="row" alignItems="center" justifyContent="space-between"><Box><Typography variant="h4">Dashboard</Typography><Typography color="text.secondary">At-a-glance API balances, usage, and provider status.</Typography></Box><Button variant="contained" startIcon={<RefreshIcon />} onClick={() => load(true)} disabled={loading}>Poll providers</Button></Stack>{homepage && <Grid container spacing={2}>{[['Configured', homepage.configured_providers], ['Healthy', homepage.healthy_providers], ['Degraded', homepage.degraded_providers], ['Summary', homepage.summary]].map(([k, v]) => <Grid size={{ xs: 12, md: 3 }} key={k}><Card><CardContent><Typography color="text.secondary" variant="overline">{k}</Typography><Typography variant="h5">{v}</Typography></CardContent></Card></Grid>)}</Grid>}{error && <Alert severity="error">{error}</Alert>}{loading && <CircularProgress />}{!loading && items.length === 0 && <Alert severity="info">No providers configured. Settings awaits, ominously.</Alert>}<Grid container spacing={2}>{items.map((item) => <Grid size={{ xs: 12, md: 6, xl: 4 }} key={item.config.id}><UsageCard item={item} /></Grid>)}</Grid></Stack>
}
