import { useEffect, useState } from 'react'
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Select, Stack, Switch, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import AddIcon from '@mui/icons-material/Add'
import DeleteIcon from '@mui/icons-material/Delete'
import { api } from '../api.js'
const initialForm = { provider: 'firecrawl', label: '', api_key: '', base_url: '' }
export default function SettingsPage() {
  const [providers, setProviders] = useState([]); const [configs, setConfigs] = useState([]); const [open, setOpen] = useState(false); const [form, setForm] = useState(initialForm); const [error, setError] = useState('')
  async function load() { try { const [p, c] = await Promise.all([api.providers(), api.configs()]); setProviders(p); setConfigs(c) } catch (err) { setError(err.message) } }
  useEffect(() => { load() }, [])
  async function submit() { setError(''); try { await api.createConfig({ ...form, base_url: form.base_url || null }); setOpen(false); setForm(initialForm); await load() } catch (err) { setError(err.message) } }
  async function remove(id) { await api.deleteConfig(id); await load() }
  async function toggle(cfg) { await api.updateConfig(cfg.id, { is_enabled: !cfg.is_enabled }); await load() }
  return <Stack gap={3}><Stack direction="row" alignItems="center" justifyContent="space-between"><Box><Typography variant="h4">Settings</Typography><Typography color="text.secondary">Add Firecrawl, DeepSeek, and OpenAI/Codex credentials. Keys are encrypted before storage.</Typography></Box><Button variant="contained" startIcon={<AddIcon />} onClick={() => setOpen(true)}>Add provider</Button></Stack>{error && <Alert severity="error">{error}</Alert>}<Table><TableHead><TableRow><TableCell>Enabled</TableCell><TableCell>Provider</TableCell><TableCell>Label</TableCell><TableCell>API key</TableCell><TableCell>Base URL</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{configs.map((cfg) => <TableRow key={cfg.id}><TableCell><Switch checked={cfg.is_enabled} onChange={() => toggle(cfg)} /></TableCell><TableCell>{cfg.provider}</TableCell><TableCell>{cfg.label}</TableCell><TableCell>{cfg.api_key_masked}</TableCell><TableCell>{cfg.base_url || 'default'}</TableCell><TableCell align="right"><Button color="error" startIcon={<DeleteIcon />} onClick={() => remove(cfg.id)}>Remove</Button></TableCell></TableRow>)}</TableBody></Table><Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Add API provider</DialogTitle><DialogContent><Stack gap={2} sx={{ mt: 1 }}><FormControl fullWidth><InputLabel>Provider</InputLabel><Select label="Provider" value={form.provider} onChange={(e) => setForm({ ...form, provider: e.target.value })}>{providers.map((p) => <MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>)}</Select></FormControl><TextField label="Label" value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} placeholder="main" /><TextField label="API key" value={form.api_key} type="password" onChange={(e) => setForm({ ...form, api_key: e.target.value })} /><TextField label="Base URL override" value={form.base_url} onChange={(e) => setForm({ ...form, base_url: e.target.value })} placeholder="Optional" /></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" onClick={submit}>Save</Button></DialogActions></Dialog></Stack>
}
